---
name: Acme-Rautavistic-Sort
version: 0.01
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
abstract: Rautavistic sort functions
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Acme::Rautavistic::Sort:
    file: lib/Acme/Rautavistic/Sort.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
